[package]
name = "lp_raw_log_exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
chrono = "0.4.38"
rayon = "1.10.0"
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.30"
